-- MySQL Script generated by MySQL Workbench
-- Sun Jun  5 09:43:12 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema statera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Table `taxclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxclass` ;

CREATE TABLE IF NOT EXISTS `taxclass` (
  `idtaxclass` INT NOT NULL AUTO_INCREMENT,
  `taxclass_deleted` TINYINT NULL DEFAULT 0,
  `taxclass_name` VARCHAR(20) NULL,
  `taxclass_description` VARCHAR(60) NULL,
  `taxclass_invoice_text` VARCHAR(40) NULL,
  PRIMARY KEY (`idtaxclass`),
  INDEX `valid` (`idtaxclass` ASC, `taxclass_deleted` ASC),
  INDEX `name` (`taxclass_name` ASC, `taxclass_deleted` ASC),
  UNIQUE INDEX `taxclass_name_UNIQUE` (`taxclass_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `chart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `chart` ;

CREATE TABLE IF NOT EXISTS `chart` (
  `chart_code` INT NOT NULL,
  `chart_deleted` TINYINT NULL DEFAULT 0,
  `chart_type` ENUM('cash', 'income', 'expense', 'current asset', 'current liability', 'liability', 'equity', 'tax') NULL,
  `chart_description_dr` VARCHAR(40) NULL,
  `chart_type_name` VARCHAR(40) NULL,
  `chart_subtype` VARCHAR(45) NULL,
  `chart_description` VARCHAR(40) NULL,
  `chart_taxclass` INT NULL,
  `chart_description_cr` VARCHAR(40) NULL,
  `chart_balancesheet` ENUM('asset', 'liability', 'revenue', 'expense', 'tax') NULL,
  `chart_balancesheet_subtype` VARCHAR(45) NULL,
  PRIMARY KEY (`chart_code`),
  INDEX `fk_chart_taxclass_idx` (`chart_taxclass` ASC),
  UNIQUE INDEX `chart_code_UNIQUE` (`chart_code` ASC),
  CONSTRAINT `fk_chart_taxclass`
    FOREIGN KEY (`chart_taxclass`)
    REFERENCES `taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `taxrate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `taxrate` ;

CREATE TABLE IF NOT EXISTS `taxrate` (
  `idtaxrate` INT NOT NULL AUTO_INCREMENT,
  `taxrate_deleted` TINYINT NULL DEFAULT 0,
  `taxrate_taxclass` INT NULL,
  `taxrate_from_date` DATE NULL,
  `taxrate_rate` DOUBLE NULL,
  `taxrate_comments` VARCHAR(200) NULL,
  PRIMARY KEY (`idtaxrate`),
  INDEX `fk_taxrate_taxclass1_idx` (`taxrate_taxclass` ASC),
  CONSTRAINT `fk_taxrate_taxclass1`
    FOREIGN KEY (`taxrate_taxclass`)
    REFERENCES `taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `user` ;

CREATE TABLE IF NOT EXISTS `user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_randid` VARCHAR(16) NOT NULL,
  `user_username` VARCHAR(100) UNIQUE NOT NULL,
  `user_lastname` VARCHAR(100) NULL,
  `user_firstname` VARCHAR(100) NULL,
  `user_email` VARCHAR(256) UNIQUE NULL,
  `user_forcereset` TINYINT NULL DEFAULT 1,
  `user_hash` VARCHAR(64) NULL,
  `user_salt` VARCHAR(64) NULL,
  `user_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_security` INT NULL DEFAULT 0,
  `user_last_signin` DATETIME NULL,
  `user_expires` DATETIME NULL,
  `user_prev_hash` VARCHAR(1600) NULL,
  `user_prev_salt` VARCHAR(1600) NULL,
  `user_disabled` TINYINT NULL DEFAULT 0,
  `user_timezone` VARCHAR(50) NULL,
  `user_failed_signin_count` INT NULL DEFAULT 0,
  `user_pw_renew_date` DATETIME NULL,
  `user_pw_change_date` DATETIME NULL,
  `user_x509_serial` VARCHAR(20) NULL,
  `user_apikey` VARCHAR(64) NULL,
  `user_remember_me` TINYINT NULL DEFAULT 0,
  `user_session_key` VARCHAR(64) NULL,
  `user_session_data` VARCHAR(8000) NULL,
  `user_undolist` VARCHAR(8000) NULL,
  PRIMARY KEY (`iduser`, `user_deleted`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC),
  UNIQUE INDEX `user_randid_UNIQUE` (`user_randid` ASC));


-- -----------------------------------------------------
-- Table `rolling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rolling` ;

CREATE TABLE IF NOT EXISTS `rolling` (
  `rolling_entity` VARCHAR(45) UNIQUE NOT NULL,
  `rolling_entity_disabled` TINYINT NULL,
  `rolling_modulus` INT NULL DEFAULT 10,
  `rolling_counters` VARCHAR(500) NULL,
  `rolling_idx` INT NULL,
  `rolling_target` DOUBLE NULL,
  `rolling_disable_seconds` INT NULL,
  `rolling_disable_timestamp` DATETIME NULL,
  PRIMARY KEY (`rolling_entity`));


-- -----------------------------------------------------
-- Table `global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `global` ;

CREATE TABLE IF NOT EXISTS `global` (
  `global_default_homepage` VARCHAR(100) NULL DEFAULT NULL,
  `global_default_domainname` VARCHAR(256) NULL DEFAULT NULL,
  `global_password_min_length` INT NULL DEFAULT 8,
  `global_password_min_num` INT NULL DEFAULT 1,
  `global_password_min_upper` INT NULL DEFAULT 1,
  `global_password_min_lower` INT NULL DEFAULT 1,
  `global_password_min_special` INT NULL DEFAULT 0,
  `global_password_renew_days` INT NULL DEFAULT 0,
  `global_password_no_renew_within_hours` INT NULL DEFAULT 0,
  `global_password_maxattempts` INT NULL DEFAULT 6,
  `global_undolist_max_depth` INT NULL DEFAULT 20,
  `global_undolist_max_age` INT NULL DEFAULT 172800)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `audit` ;

CREATE TABLE IF NOT EXISTS `audit` (
  `idaudit` INT NOT NULL AUTO_INCREMENT,
  `audit_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `audit_type` VARCHAR(45) NULL,
  `audit_description` VARCHAR(500) NULL,
  `audit_user` INT NULL,
  PRIMARY KEY (`idaudit`, `audit_timestamp`),
  INDEX `type` (`audit_type` ASC, `audit_timestamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account` ;

CREATE TABLE IF NOT EXISTS `account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `account_deleted` TINYINT NULL DEFAULT 0,
  `account_name` VARCHAR(100) NULL,
  `account_email` VARCHAR(256) NULL,
  `account_phone` VARCHAR(21) NULL,
  `account_address1` VARCHAR(100) NULL,
  `account_address2` VARCHAR(45) NULL,
  `account_address3` VARCHAR(45) NULL,
  `account_address4` VARCHAR(45) NULL,
  `account_city` VARCHAR(60) NULL,
  `account_postcode` VARCHAR(20) NULL,
  `account_state` VARCHAR(40) NULL,
  `account_country` VARCHAR(60) NULL,
  `account_contact_accounts` VARCHAR(100) NULL,
  `account_sale_tax_class` INT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `fk_account_taxclass1_idx` (`account_sale_tax_class` ASC),
  CONSTRAINT `fk_account_taxclass1`
    FOREIGN KEY (`account_sale_tax_class`)
    REFERENCES `taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice` ;

CREATE TABLE IF NOT EXISTS `invoice` (
  `idinvoice` INT NOT NULL AUTO_INCREMENT,
  `invoice_deleted` TINYINT NULL DEFAULT 0,
  `invoice_date` DATE NULL,
  `invoice_number` INT NULL,
  `invoice_cash_sale` TINYINT NULL DEFAULT 0,
  `invoice_account` INT NULL,
  `invoice_company_name` VARCHAR(45) NULL,
  `invoice_company_address1` VARCHAR(100) NULL,
  `invoice_company_address2` VARCHAR(100) NULL,
  `invoice_company_address3` VARCHAR(100) NULL,
  `invoice_company_address4` VARCHAR(100) NULL,
  `invoice_company_city` VARCHAR(60) NULL,
  `invoice_company_postcode` VARCHAR(20) NULL,
  `invoice_company_country` VARCHAR(60) NULL,
  `invoice_sale_tax_class` INT NULL,
  `invoice_sale_tax_name` VARCHAR(40) NULL,
  `invoice_tax_number` VARCHAR(45) NULL,
  `invoice_bank_acct_name` VARCHAR(45) NULL,
  `invoice_bank_acct_number` VARCHAR(45) NULL,
  `invoice_account_name` VARCHAR(100) NULL,
  `invoice_account_address1` VARCHAR(100) NULL,
  `invoice_account_address2` VARCHAR(100) NULL,
  `invoice_account_address3` VARCHAR(100) NULL,
  `invoice_account_address4` VARCHAR(100) NULL,
  `invoice_account_city` VARCHAR(60) NULL,
  `invoice_account_state` VARCHAR(40) NULL,
  `invoice_account_postcode` VARCHAR(20) NULL,
  `invoice_account_country` VARCHAR(60) NULL,
  `invoice_account_ref1` VARCHAR(45) NULL,
  `invoice_account_ref2` VARCHAR(45) NULL,
  PRIMARY KEY (`idinvoice`),
  UNIQUE INDEX `invoice_number_UNIQUE` (`invoice_number` ASC),
  INDEX `fk_invoice_account1_idx` (`invoice_account` ASC),
  INDEX `fk_invoice_taxclass1_idx` (`invoice_sale_tax_class` ASC),
  CONSTRAINT `fk_invoice_account1`
    FOREIGN KEY (`invoice_account`)
    REFERENCES `account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_taxclass1`
    FOREIGN KEY (`invoice_sale_tax_class`)
    REFERENCES `taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `shareholder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `shareholder` ;

CREATE TABLE IF NOT EXISTS `shareholder` (
  `idshareholder` INT NOT NULL AUTO_INCREMENT,
  `shareholder_deleted` TINYINT NULL DEFAULT 0,
  `shareholder_lastname` VARCHAR(60) NULL,
  `shareholder_firstnames` VARCHAR(100) NULL,
  PRIMARY KEY (`idshareholder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `asset` ;

CREATE TABLE IF NOT EXISTS `asset` (
  `idasset` INT NOT NULL AUTO_INCREMENT,
  `asset_name` VARCHAR(45) NULL,
  `asset_purhcase_date` DATE NULL,
  `asset_depreciation_method` ENUM('dv', 'sl') NULL,
  `asset_depreciation_rate` DOUBLE NULL,
  PRIMARY KEY (`idasset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `staff` ;

CREATE TABLE IF NOT EXISTS `staff` (
  `idstaff` INT NOT NULL AUTO_INCREMENT,
  `staff_deleted` TINYINT NULL DEFAULT 0,
  `staff_name` VARCHAR(100) NOT NULL,
  `staff_email` VARCHAR(256) NULL,
  PRIMARY KEY (`idstaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `journal` ;

CREATE TABLE IF NOT EXISTS `journal` (
  `idjournal` INT NOT NULL AUTO_INCREMENT,
  `journal_xtn` INT NULL,
  `journal_date` DATE NULL,
  `journal_chart` INT NULL,
  `journal_description` VARCHAR(100) NULL,
  `journal_net` DECIMAL(11,2) NULL,
  `journal_tax` DECIMAL(11,2) NULL,
  `journal_gross` DECIMAL(11,2) NULL,
  `journal_link` INT NULL,
  `journal_source` INT NULL,
  `journal_source_chart` INT NULL,
  `journal_folio` INT NULL,
  `journal_account` INT NULL,
  `journal_invoice` INT NULL,
  `journal_asset` INT NULL,
  `journal_tax_date` DATE NULL,
  `journal_shareholder` INT NULL,
  `journal_staff` INT NULL,
  `journal_vendor_name` VARCHAR(100) NULL,
  `journal_vendor_tax_number` VARCHAR(40) NULL,
  PRIMARY KEY (`idjournal`),
  INDEX `fk_journal_account1_idx` (`journal_account` ASC),
  INDEX `fk_journal_chart1_idx` (`journal_chart` ASC),
  INDEX `fk_journal_invoice1_idx` (`journal_invoice` ASC),
  INDEX `xtn` (`journal_xtn` ASC),
  INDEX `fk_journal_shareholder1_idx` (`journal_shareholder` ASC),
  INDEX `fk_journal_asset1_idx` (`journal_asset` ASC),
  INDEX `fk_journal_chart2_idx` (`journal_source_chart` ASC),
  INDEX `fk_journal_staff1_idx` (`journal_staff` ASC),
  CONSTRAINT `fk_journal_account1`
    FOREIGN KEY (`journal_account`)
    REFERENCES `account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_chart1`
    FOREIGN KEY (`journal_chart`)
    REFERENCES `chart` (`chart_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_invoice1`
    FOREIGN KEY (`journal_invoice`)
    REFERENCES `invoice` (`idinvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_shareholder1`
    FOREIGN KEY (`journal_shareholder`)
    REFERENCES `shareholder` (`idshareholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_asset1`
    FOREIGN KEY (`journal_asset`)
    REFERENCES `asset` (`idasset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_chart2`
    FOREIGN KEY (`journal_source_chart`)
    REFERENCES `chart` (`chart_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_staff1`
    FOREIGN KEY (`journal_staff`)
    REFERENCES `staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product` ;

CREATE TABLE IF NOT EXISTS `product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `product_deleted` TINYINT NULL DEFAULT 0,
  `product_order` INT NULL DEFAULT 0,
  `product_description` VARCHAR(100) NOT NULL,
  `product_type` ENUM('service', 'goods') NULL,
  `product_unit_cost` DECIMAL(11,2) NULL,
  `product_unit_text` VARCHAR(20) NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `order` (`product_deleted` ASC, `product_order` DESC, `product_description` ASC),
  UNIQUE INDEX `product_description_UNIQUE` (`product_description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `invoice_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `invoice_line` ;

CREATE TABLE IF NOT EXISTS `invoice_line` (
  `idinvoice_line` INT NOT NULL AUTO_INCREMENT,
  `invoice_line_invoice` INT NULL,
  `invoice_line_product` INT NULL,
  `invoice_line_description` VARCHAR(500) NULL,
  `invoice_line_qty` DOUBLE NULL DEFAULT 0.00,
  `invoice_line_unit_desc` VARCHAR(45) NULL,
  `invoice_line_unit_cost` DECIMAL(11,2) NULL,
  `invoice_line_total_cost` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idinvoice_line`),
  INDEX `fk_invoice_line_invoice1_idx` (`invoice_line_invoice` ASC),
  INDEX `fk_invoice_line_product1_idx` (`invoice_line_product` ASC),
  CONSTRAINT `fk_invoice_line_invoice1`
    FOREIGN KEY (`invoice_line_invoice`)
    REFERENCES `invoice` (`idinvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_line_product1`
    FOREIGN KEY (`invoice_line_product`)
    REFERENCES `product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `company` ;

CREATE TABLE IF NOT EXISTS `company` (
  `company_name` VARCHAR(45) NULL,
  `company_address1` VARCHAR(100) NULL,
  `company_address2` VARCHAR(100) NULL,
  `company_address3` VARCHAR(100) NULL,
  `company_address4` VARCHAR(100) NULL,
  `company_city` VARCHAR(60) NULL,
  `company_postcode` VARCHAR(20) NULL,
  `company_state` VARCHAR(45) NULL,
  `company_country` VARCHAR(60) NULL,
  `company_country_prefix` VARCHAR(6) NULL,
  `company_email` VARCHAR(256) NULL,
  `company_phone` VARCHAR(21) NULL,
  `company_start_date` DATE NULL,
  `company_tax_number` VARCHAR(45) NULL,
  `company_bank_acct_name` VARCHAR(45) NULL,
  `company_bank_acct_number` VARCHAR(45) NULL,
  `company_sales_tax_name` VARCHAR(20) NULL,
  `company_sales_tax_cadence` INT NULL,
  `company_sales_tax_first_month` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `share` ;

CREATE TABLE IF NOT EXISTS `share` (
  `idshare` INT NOT NULL AUTO_INCREMENT,
  `share_date` DATE NULL,
  `share_qty` INT NULL,
  `share_buyprice` DECIMAL(11,2) NULL,
  `share_shareholder` INT NULL,
  PRIMARY KEY (`idshare`),
  INDEX `fk_share_shareholder1_idx` (`share_shareholder` ASC),
  CONSTRAINT `fk_share_shareholder1`
    FOREIGN KEY (`share_shareholder`)
    REFERENCES `shareholder` (`idshareholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
