-- MySQL Script generated by MySQL Workbench
-- Sat Feb 21 08:36:21 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema statera
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema statera
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `statera` DEFAULT CHARACTER SET utf8 ;
USE `statera` ;

-- -----------------------------------------------------
-- Table `statera`.`taxclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`taxclass` ;

CREATE TABLE IF NOT EXISTS `statera`.`taxclass` (
  `idtaxclass` INT NOT NULL AUTO_INCREMENT,
  `taxclass_deleted` TINYINT NULL DEFAULT 0,
  `taxclass_name` VARCHAR(20) NULL,
  `taxclass_description` VARCHAR(60) NULL,
  `taxclass_invoice_text` VARCHAR(40) NULL,
  PRIMARY KEY (`idtaxclass`),
  INDEX `valid` (`idtaxclass` ASC, `taxclass_deleted` ASC),
  INDEX `name` (`taxclass_name` ASC, `taxclass_deleted` ASC),
  UNIQUE INDEX `taxclass_name_UNIQUE` (`taxclass_name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`chart`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`chart` ;

CREATE TABLE IF NOT EXISTS `statera`.`chart` (
  `chart_code` INT NOT NULL,
  `chart_deleted` TINYINT NULL DEFAULT 0,
  `chart_type` ENUM('cash', 'income', 'expense', 'current asset', 'current liability', 'non current liability', 'asset', 'liability', 'equity', 'tax') NULL,
  `chart_description_dr` VARCHAR(40) NULL,
  `chart_type_name` VARCHAR(40) NULL,
  `chart_subtype` VARCHAR(45) NULL,
  `chart_subsubtype` VARCHAR(45) NULL,
  `chart_description` VARCHAR(40) NULL,
  `chart_taxclass` INT NULL,
  `chart_description_cr` VARCHAR(40) NULL,
  `chart_balancesheet` ENUM('asset', 'liability', 'revenue', 'expense', 'tax') NULL,
  `chart_balancesheet_subtype` VARCHAR(45) NULL,
  PRIMARY KEY (`chart_code`),
  INDEX `fk_chart_taxclass_idx` (`chart_taxclass` ASC),
  UNIQUE INDEX `chart_code_UNIQUE` (`chart_code` ASC),
  CONSTRAINT `fk_chart_taxclass`
    FOREIGN KEY (`chart_taxclass`)
    REFERENCES `statera`.`taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`taxrate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`taxrate` ;

CREATE TABLE IF NOT EXISTS `statera`.`taxrate` (
  `idtaxrate` INT NOT NULL AUTO_INCREMENT,
  `taxrate_deleted` TINYINT NULL DEFAULT 0,
  `taxrate_taxclass` INT NULL,
  `taxrate_from_date` DATE NULL,
  `taxrate_rate` DOUBLE NULL,
  `taxrate_comments` VARCHAR(200) NULL,
  PRIMARY KEY (`idtaxrate`),
  INDEX `fk_taxrate_taxclass1_idx` (`taxrate_taxclass` ASC),
  CONSTRAINT `fk_taxrate_taxclass1`
    FOREIGN KEY (`taxrate_taxclass`)
    REFERENCES `statera`.`taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`user` ;

CREATE TABLE IF NOT EXISTS `statera`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `user_deleted` TINYINT NOT NULL DEFAULT 0,
  `user_randid` VARCHAR(16) NOT NULL,
  `user_username` VARCHAR(100) UNIQUE NOT NULL,
  `user_lastname` VARCHAR(100) NULL,
  `user_firstname` VARCHAR(100) NULL,
  `user_email` VARCHAR(256) UNIQUE NULL,
  `user_phone` VARCHAR(21) NULL,
  `user_forcereset` TINYINT NULL DEFAULT 1,
  `user_hash` VARCHAR(64) NULL,
  `user_salt` VARCHAR(64) NULL,
  `user_createtime` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `user_security` INT NULL DEFAULT 0,
  `user_last_signin` DATETIME NULL,
  `user_expires` DATETIME NULL,
  `user_prev_hash` VARCHAR(1600) NULL,
  `user_prev_salt` VARCHAR(1600) NULL,
  `user_disabled` TINYINT NULL DEFAULT 0,
  `user_timezone` VARCHAR(50) NULL,
  `user_failed_signin_count` INT NULL DEFAULT 0,
  `user_pw_renew_date` DATETIME NULL,
  `user_pw_change_date` DATETIME NULL,
  `user_x509_serial` VARCHAR(20) NULL,
  `user_apikey` VARCHAR(64) NULL,
  `user_remember_me` TINYINT NULL DEFAULT 0,
  `user_session_key` VARCHAR(64) NULL,
  `user_session_data` VARCHAR(4000) NULL,
  `user_undolist` VARCHAR(4000) NULL,
  `user_notify_quotes` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`iduser`, `user_deleted`),
  UNIQUE INDEX `user_username_UNIQUE` (`user_username` ASC),
  UNIQUE INDEX `user_randid_UNIQUE` (`user_randid` ASC));


-- -----------------------------------------------------
-- Table `statera`.`rolling`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`rolling` ;

CREATE TABLE IF NOT EXISTS `statera`.`rolling` (
  `rolling_entity` VARCHAR(45) UNIQUE NOT NULL,
  `rolling_entity_disabled` TINYINT NULL,
  `rolling_modulus` INT NULL DEFAULT 10,
  `rolling_counters` VARCHAR(500) NULL,
  `rolling_idx` INT NULL,
  `rolling_target` DOUBLE NULL,
  `rolling_disable_seconds` INT NULL,
  `rolling_disable_timestamp` DATETIME NULL,
  PRIMARY KEY (`rolling_entity`));


-- -----------------------------------------------------
-- Table `statera`.`global`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`global` ;

CREATE TABLE IF NOT EXISTS `statera`.`global` (
  `global_default_homepage` VARCHAR(100) NULL DEFAULT NULL,
  `global_default_domainname` VARCHAR(256) NULL DEFAULT NULL,
  `global_password_min_length` INT NULL DEFAULT 8,
  `global_password_min_num` INT NULL DEFAULT 1,
  `global_password_min_upper` INT NULL DEFAULT 1,
  `global_password_min_lower` INT NULL DEFAULT 1,
  `global_password_min_special` INT NULL DEFAULT 0,
  `global_password_renew_days` INT NULL DEFAULT 0,
  `global_password_no_renew_within_hours` INT NULL DEFAULT 0,
  `global_password_maxattempts` INT NULL DEFAULT 6,
  `global_undolist_max_depth` INT NULL DEFAULT 20,
  `global_undolist_max_age` INT NULL DEFAULT 172800)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`audit`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`audit` ;

CREATE TABLE IF NOT EXISTS `statera`.`audit` (
  `idaudit` INT NOT NULL AUTO_INCREMENT,
  `audit_timestamp` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `audit_type` VARCHAR(45) NULL,
  `audit_description` VARCHAR(500) NULL,
  `audit_user` INT NULL,
  PRIMARY KEY (`idaudit`, `audit_timestamp`),
  INDEX `type` (`audit_type` ASC, `audit_timestamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`account` ;

CREATE TABLE IF NOT EXISTS `statera`.`account` (
  `idaccount` INT NOT NULL AUTO_INCREMENT,
  `account_deleted` TINYINT NULL DEFAULT 0,
  `account_name` VARCHAR(100) NULL,
  `account_email` VARCHAR(256) NULL,
  `account_phone` VARCHAR(21) NULL,
  `account_address1` VARCHAR(100) NULL,
  `account_address2` VARCHAR(45) NULL,
  `account_address3` VARCHAR(45) NULL,
  `account_address4` VARCHAR(45) NULL,
  `account_city` VARCHAR(60) NULL,
  `account_postcode` VARCHAR(20) NULL,
  `account_state` VARCHAR(40) NULL,
  `account_country` VARCHAR(60) NULL,
  `account_contact_accounts` VARCHAR(100) NULL,
  `account_sale_tax_class` INT NULL,
  PRIMARY KEY (`idaccount`),
  INDEX `fk_account_taxclass1_idx` (`account_sale_tax_class` ASC),
  CONSTRAINT `fk_account_taxclass1`
    FOREIGN KEY (`account_sale_tax_class`)
    REFERENCES `statera`.`taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`invoice`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`invoice` ;

CREATE TABLE IF NOT EXISTS `statera`.`invoice` (
  `idinvoice` INT NOT NULL AUTO_INCREMENT,
  `invoice_deleted` TINYINT NULL DEFAULT 0,
  `invoice_date` DATE NULL,
  `invoice_number` INT NULL,
  `invoice_cash_sale` TINYINT NULL DEFAULT 0,
  `invoice_account` INT NULL,
  `invoice_company_name` VARCHAR(45) NULL,
  `invoice_company_address1` VARCHAR(100) NULL,
  `invoice_company_address2` VARCHAR(100) NULL,
  `invoice_company_address3` VARCHAR(100) NULL,
  `invoice_company_address4` VARCHAR(100) NULL,
  `invoice_company_city` VARCHAR(60) NULL,
  `invoice_company_postcode` VARCHAR(20) NULL,
  `invoice_company_country` VARCHAR(60) NULL,
  `invoice_sale_tax_class` INT NULL,
  `invoice_sale_tax_name` VARCHAR(40) NULL,
  `invoice_tax_number` VARCHAR(45) NULL,
  `invoice_bank_acct_name` VARCHAR(45) NULL,
  `invoice_bank_acct_number` VARCHAR(45) NULL,
  `invoice_account_name` VARCHAR(100) NULL,
  `invoice_account_address1` VARCHAR(100) NULL,
  `invoice_account_address2` VARCHAR(100) NULL,
  `invoice_account_address3` VARCHAR(100) NULL,
  `invoice_account_address4` VARCHAR(100) NULL,
  `invoice_account_city` VARCHAR(60) NULL,
  `invoice_account_state` VARCHAR(40) NULL,
  `invoice_account_postcode` VARCHAR(20) NULL,
  `invoice_account_country` VARCHAR(60) NULL,
  `invoice_account_ref1` VARCHAR(45) NULL,
  `invoice_account_ref2` VARCHAR(45) NULL,
  PRIMARY KEY (`idinvoice`),
  UNIQUE INDEX `invoice_number_UNIQUE` (`invoice_number` ASC),
  INDEX `fk_invoice_account1_idx` (`invoice_account` ASC),
  INDEX `fk_invoice_taxclass1_idx` (`invoice_sale_tax_class` ASC),
  CONSTRAINT `fk_invoice_account1`
    FOREIGN KEY (`invoice_account`)
    REFERENCES `statera`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_taxclass1`
    FOREIGN KEY (`invoice_sale_tax_class`)
    REFERENCES `statera`.`taxclass` (`idtaxclass`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`shareholder`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`shareholder` ;

CREATE TABLE IF NOT EXISTS `statera`.`shareholder` (
  `idshareholder` INT NOT NULL AUTO_INCREMENT,
  `shareholder_deleted` TINYINT NULL DEFAULT 0,
  `shareholder_lastname` VARCHAR(60) NULL,
  `shareholder_firstnames` VARCHAR(100) NULL,
  PRIMARY KEY (`idshareholder`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`asset`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`asset` ;

CREATE TABLE IF NOT EXISTS `statera`.`asset` (
  `idasset` INT NOT NULL AUTO_INCREMENT,
  `asset_name` VARCHAR(45) NULL,
  `asset_purhcase_date` DATE NULL,
  `asset_depreciation_method` ENUM('dv', 'sl') NULL,
  `asset_depreciation_rate` DOUBLE NULL,
  PRIMARY KEY (`idasset`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`staff` ;

CREATE TABLE IF NOT EXISTS `statera`.`staff` (
  `idstaff` INT NOT NULL AUTO_INCREMENT,
  `staff_deleted` TINYINT NULL DEFAULT 0,
  `staff_name` VARCHAR(100) NOT NULL,
  `staff_type` ENUM('contractor', 'casual', 'wages') NULL,
  `staff_email` VARCHAR(256) NULL,
  `staff_phone` VARCHAR(21) NULL,
  `staff_start_date` DATE NULL,
  `staff_tax_number` VARCHAR(20) NULL,
  `staff_tax_code` VARCHAR(8) NULL,
  `staff_bank_acct_number` VARCHAR(24) NULL,
  `staff_bank_acct_name` VARCHAR(60) NULL,
  `staff_list_on_timesheet` TINYINT NULL,
  `staff_hourly_rate1` DECIMAL(5,2) NULL DEFAULT 0.0,
  `staff_hourly_rate2` DECIMAL(5,2) NULL DEFAULT 0.0,
  `staff_hourly_rate3` DECIMAL(5,2) NULL DEFAULT 0.0,
  `staff_add_holiday_pay` TINYINT NULL DEFAULT 0,
  `staff_holiday_pay_rate` DOUBLE NULL,
  `staff_has_kiwi_saver` TINYINT NULL DEFAULT 0,
  `staff_kiwi_save_employer_rate` DOUBLE NULL,
  `staff_kiwi_save_employee_rate` DOUBLE NULL,
  `staff_use_esct_tax` TINYINT NULL DEFAULT 0,
  `staff_esct_tax_rate` DOUBLE NULL,
  PRIMARY KEY (`idstaff`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`quote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`quote` ;

CREATE TABLE IF NOT EXISTS `statera`.`quote` (
  `idquote` INT NOT NULL AUTO_INCREMENT,
  `quote_deleted` TINYINT NULL DEFAULT 0,
  `quote_number` INT NULL,
  `quote_date` DATE NULL,
  `quote_customer_account` INT NULL,
  `quote_contact_name` VARCHAR(100) NULL,
  `quote_contact_phone` VARCHAR(21) NULL,
  `quote_contact_email` VARCHAR(256) NULL,
  `quote_status` ENUM('open', 'accepted', 'completed') NULL DEFAULT 'open',
  `quote_accept_date` DATE NULL DEFAULT NULL,
  `quote_value_net` DECIMAL(11,2) NULL,
  `quote_value_tax` DECIMAL(11,2) NULL,
  `quote_value_gross` DECIMAL(11,2) NULL,
  `quote_address1` VARCHAR(60) NULL,
  `quote_address2` VARCHAR(60) NULL,
  `quote_address3` VARCHAR(60) NULL,
  `quote_address4` VARCHAR(60) NULL,
  `quote_city` VARCHAR(60) NULL,
  `quote_option_no_item_cost` TINYINT NULL DEFAULT 1,
  `quote_accepted_timestamp` DATETIME NULL,
  `quote_denied_timestamp` DATETIME NULL,
  `quote_completed_timestamp` DATETIME NULL,
  PRIMARY KEY (`idquote`),
  UNIQUE INDEX `bynumber` (`quote_number` ASC),
  INDEX `fk_quote_account1_idx` (`quote_customer_account` ASC),
  CONSTRAINT `fk_quote_account1`
    FOREIGN KEY (`quote_customer_account`)
    REFERENCES `statera`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`journal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`journal` ;

CREATE TABLE IF NOT EXISTS `statera`.`journal` (
  `idjournal` INT NOT NULL AUTO_INCREMENT,
  `journal_xtn` INT NULL,
  `journal_date` DATE NULL,
  `journal_chart` INT NULL,
  `journal_marker` ENUM('starteoy', 'endeoy') NULL,
  `journal_description` VARCHAR(100) NULL,
  `journal_net` DECIMAL(11,2) NULL,
  `journal_tax` DECIMAL(11,2) NULL,
  `journal_gross` DECIMAL(11,2) NULL,
  `journal_wage_tax` DECIMAL(11,2) NULL,
  `journal_tax_type` VARCHAR(20) NULL,
  `journal_link` INT NULL,
  `journal_source` INT NULL,
  `journal_source_chart` INT NULL,
  `journal_folio` INT NULL,
  `journal_quote` INT NULL,
  `journal_account` INT NULL,
  `journal_invoice` INT NULL,
  `journal_asset` INT NULL,
  `journal_attachment_group` INT NULL,
  `journal_tax_date` DATE NULL,
  `journal_shareholder` INT NULL,
  `journal_staff` INT NULL,
  `journal_vendor_name` VARCHAR(100) NULL,
  `journal_vendor_tax_number` VARCHAR(40) NULL,
  `journal_kiwisaver_employee` DECIMAL(11,2) NULL,
  `journal_kiwisaver_employer` DECIMAL(11,2) NULL,
  `journal_kiwisaver_esct_tax` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idjournal`),
  INDEX `fk_journal_account1_idx` (`journal_account` ASC),
  INDEX `fk_journal_chart1_idx` (`journal_chart` ASC),
  INDEX `fk_journal_invoice1_idx` (`journal_invoice` ASC),
  INDEX `xtn` (`journal_xtn` ASC),
  INDEX `fk_journal_shareholder1_idx` (`journal_shareholder` ASC),
  INDEX `fk_journal_asset1_idx` (`journal_asset` ASC),
  INDEX `fk_journal_chart2_idx` (`journal_source_chart` ASC),
  INDEX `fk_journal_staff1_idx` (`journal_staff` ASC),
  INDEX `fk_journal_quote1_idx` (`journal_quote` ASC),
  CONSTRAINT `fk_journal_account1`
    FOREIGN KEY (`journal_account`)
    REFERENCES `statera`.`account` (`idaccount`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_chart1`
    FOREIGN KEY (`journal_chart`)
    REFERENCES `statera`.`chart` (`chart_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_invoice1`
    FOREIGN KEY (`journal_invoice`)
    REFERENCES `statera`.`invoice` (`idinvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_shareholder1`
    FOREIGN KEY (`journal_shareholder`)
    REFERENCES `statera`.`shareholder` (`idshareholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_asset1`
    FOREIGN KEY (`journal_asset`)
    REFERENCES `statera`.`asset` (`idasset`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_chart2`
    FOREIGN KEY (`journal_source_chart`)
    REFERENCES `statera`.`chart` (`chart_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_staff1`
    FOREIGN KEY (`journal_staff`)
    REFERENCES `statera`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_journal_quote1`
    FOREIGN KEY (`journal_quote`)
    REFERENCES `statera`.`quote` (`idquote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`product` ;

CREATE TABLE IF NOT EXISTS `statera`.`product` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `product_deleted` TINYINT NULL DEFAULT 0,
  `product_order` INT NULL DEFAULT 0,
  `product_description` VARCHAR(100) NOT NULL,
  `product_type` ENUM('service', 'goods') NULL,
  `product_unit_cost` DECIMAL(11,2) NULL,
  `product_unit_text` VARCHAR(20) NULL,
  PRIMARY KEY (`idproduct`),
  INDEX `order` (`product_deleted` ASC, `product_order` DESC, `product_description` ASC),
  UNIQUE INDEX `product_description_UNIQUE` (`product_description` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`invoice_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`invoice_line` ;

CREATE TABLE IF NOT EXISTS `statera`.`invoice_line` (
  `idinvoice_line` INT NOT NULL AUTO_INCREMENT,
  `invoice_line_invoice` INT NULL,
  `invoice_line_product` INT NULL,
  `invoice_line_description` VARCHAR(500) NULL,
  `invoice_line_qty` DOUBLE NULL DEFAULT 0.00,
  `invoice_line_unit_desc` VARCHAR(45) NULL,
  `invoice_line_unit_cost` DECIMAL(11,2) NULL,
  `invoice_line_net_cost` DECIMAL(11,2) NULL,
  `invoice_line_tax_cost` DECIMAL(11,2) NULL,
  `invoice_line_gross_cost` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idinvoice_line`),
  INDEX `fk_invoice_line_invoice1_idx` (`invoice_line_invoice` ASC),
  INDEX `fk_invoice_line_product1_idx` (`invoice_line_product` ASC),
  CONSTRAINT `fk_invoice_line_invoice1`
    FOREIGN KEY (`invoice_line_invoice`)
    REFERENCES `statera`.`invoice` (`idinvoice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_invoice_line_product1`
    FOREIGN KEY (`invoice_line_product`)
    REFERENCES `statera`.`product` (`idproduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`company`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`company` ;

CREATE TABLE IF NOT EXISTS `statera`.`company` (
  `company_name` VARCHAR(45) NULL,
  `company_address1` VARCHAR(100) NULL,
  `company_address2` VARCHAR(100) NULL,
  `company_address3` VARCHAR(100) NULL,
  `company_address4` VARCHAR(100) NULL,
  `company_city` VARCHAR(60) NULL,
  `company_postcode` VARCHAR(20) NULL,
  `company_state` VARCHAR(45) NULL,
  `company_country` VARCHAR(60) NULL,
  `company_country_prefix` VARCHAR(6) NULL,
  `company_email` VARCHAR(256) NULL,
  `company_phone` VARCHAR(21) NULL,
  `company_start_date` DATE NULL,
  `company_tax_number` VARCHAR(45) NULL,
  `company_bank_acct_name` VARCHAR(45) NULL,
  `company_bank_acct_number` VARCHAR(45) NULL,
  `company_sales_tax_name` VARCHAR(20) NULL,
  `company_financialyear_start_month` INT NULL,
  `company_sales_tax_cadence` INT NULL,
  `company_sales_tax_first_month` INT NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`share`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`share` ;

CREATE TABLE IF NOT EXISTS `statera`.`share` (
  `idshare` INT NOT NULL AUTO_INCREMENT,
  `share_date` DATE NULL,
  `share_qty` INT NULL,
  `share_buyprice` DECIMAL(11,2) NULL,
  `share_shareholder` INT NULL,
  PRIMARY KEY (`idshare`),
  INDEX `fk_share_shareholder1_idx` (`share_shareholder` ASC),
  CONSTRAINT `fk_share_shareholder1`
    FOREIGN KEY (`share_shareholder`)
    REFERENCES `statera`.`shareholder` (`idshareholder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`quote_request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`quote_request` ;

CREATE TABLE IF NOT EXISTS `statera`.`quote_request` (
  `idquote_request` INT NOT NULL AUTO_INCREMENT,
  `quote_request_deleted` TINYINT NULL DEFAULT 0,
  `quote_request_date` DATE NOT NULL,
  `quote_request_name` VARCHAR(60) NULL,
  `quote_request_phone` VARCHAR(21) NULL,
  `quote_request_email` VARCHAR(256) NULL,
  `quote_request_addreess1` VARCHAR(80) NULL,
  `quote_request_addreess2` VARCHAR(80) NULL,
  `quote_request_addreess3` VARCHAR(80) NULL,
  `quote_request_addreess4` VARCHAR(80) NULL,
  `quote_request_addreess5` VARCHAR(80) NULL,
  `quote_request_comment` VARCHAR(1000) NULL,
  PRIMARY KEY (`idquote_request`, `quote_request_date`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`quote_line`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`quote_line` ;

CREATE TABLE IF NOT EXISTS `statera`.`quote_line` (
  `idquote_line` INT NOT NULL AUTO_INCREMENT,
  `quote_line_quote` INT NULL,
  `quote_line_item` INT NULL,
  `quote_line_descripton` VARCHAR(1000) NULL,
  `quote_line_qty` DOUBLE NULL,
  `quote_line_cost` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idquote_line`),
  INDEX `fk_quote_line_quote1_idx` (`quote_line_quote` ASC),
  CONSTRAINT `fk_quote_line_quote1`
    FOREIGN KEY (`quote_line_quote`)
    REFERENCES `statera`.`quote` (`idquote`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`attachment_group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`attachment_group` ;

CREATE TABLE IF NOT EXISTS `statera`.`attachment_group` (
  `idattachment_group` INT NOT NULL AUTO_INCREMENT,
  `attachment_group_timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `attachment_group_type` VARCHAR(20) NULL,
  `attachment_group_description` VARCHAR(200) NULL,
  PRIMARY KEY (`idattachment_group`),
  INDEX `index2` (`attachment_group_timestamp` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`attachment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`attachment` ;

CREATE TABLE IF NOT EXISTS `statera`.`attachment` (
  `idattachment` INT NOT NULL AUTO_INCREMENT,
  `attachment_deleted` TINYINT NULL DEFAULT 0,
  `attachment_group` INT NULL,
  `attachment_filename` VARCHAR(256) NULL,
  `attachment_original_name` VARCHAR(256) NULL,
  PRIMARY KEY (`idattachment`),
  INDEX `fk_attachment_attachment_group1_idx` (`attachment_group` ASC),
  CONSTRAINT `fk_attachment_attachment_group1`
    FOREIGN KEY (`attachment_group`)
    REFERENCES `statera`.`attachment_group` (`idattachment_group`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`timesheet`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`timesheet` ;

CREATE TABLE IF NOT EXISTS `statera`.`timesheet` (
  `idtimesheet` INT NOT NULL AUTO_INCREMENT,
  `timesheet_date` DATE NULL,
  `timesheet_type` ENUM('hours', 'directpay') NULL,
  `timesheet_staff` INT NULL,
  `timesheet_direct_gross` DECIMAL(11,2) NULL,
  `timesheet_hours` DOUBLE NULL,
  `timesheet_processed` TINYINT NULL DEFAULT 0,
  `timesheet_payxtn` INT NULL,
  `timesheet_paid_date` DATE NULL,
  `timesheet_pay_cadence` ENUM('weekly', 'fortnightly', 'monthly', 'adhoc') NULL DEFAULT 'adhoc',
  `timesheet_entry_timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `timesheet_entry_user` INT NULL,
  PRIMARY KEY (`idtimesheet`),
  INDEX `fk_timesheet_staff1_idx` (`timesheet_staff` ASC),
  INDEX `fk_timesheet_user1_idx` (`timesheet_entry_user` ASC),
  CONSTRAINT `fk_timesheet_staff1`
    FOREIGN KEY (`timesheet_staff`)
    REFERENCES `statera`.`staff` (`idstaff`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_timesheet_user1`
    FOREIGN KEY (`timesheet_entry_user`)
    REFERENCES `statera`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `statera`.`taxbracket`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `statera`.`taxbracket` ;

CREATE TABLE IF NOT EXISTS `statera`.`taxbracket` (
  `idtaxbracket` INT NOT NULL AUTO_INCREMENT,
  `taxbracket_deleted` TINYINT NULL DEFAULT 0,
  `taxbracket_from_date` DATE NULL,
  `taxbracket_amount` DECIMAL(11,2) NULL,
  `taxbracket_percent` DOUBLE NULL,
  `taxbracket_product` DECIMAL(11,2) NULL,
  PRIMARY KEY (`idtaxbracket`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
